/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef, useCallback, forwardRef, type JSX, useEffect } from 'react'
import type { MutableRefObject } from 'react'
import { useGLTF, useAnimations, useFBX } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { lerp } from 'three/src/math/MathUtils.js'


// Define explicit node/material types for useGLTF
type AvatarGLTFResult = {
  nodes: {
    Hips: THREE.Bone,
    Streamoji_Avatar: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton
    },
    EyeLeft: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
    EyeRight: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
    Streamoji_Head: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
    Streamoji_Teeth: THREE.SkinnedMesh & {
      geometry: THREE.BufferGeometry,
      skeleton: THREE.Skeleton,
      morphTargetDictionary: { [key: string]: number },
      morphTargetInfluences: number[]
    },
  },
  materials: {
    Streamoji_Avatar: THREE.Material,
    Streamoji_Eye: THREE.Material,
    Streamoji_Skin: THREE.Material,
    Streamoji_Teeth: THREE.Material
  }
}

export const Avatar = forwardRef<THREE.Group, JSX.IntrinsicElements['group']>(function Avatar(
  props,
  ref
) {
  const group = useRef<THREE.Group>(null)
  const setGroupRef = useCallback(
    (node: THREE.Group | null) => {
      group.current = node
      if (typeof ref === 'function') ref(node)
      else if (ref) (ref as MutableRefObject<THREE.Group | null>).current = node
    },
    [ref]
  )
  // Cast result as AvatarGLTFResult to inform TS about node/material structure
  const { nodes, materials } = useGLTF('models/Avatar.glb') as unknown as AvatarGLTFResult

  // Load animations from FBX files
  const walkingFBX = useFBX('/animations/Walking.fbx')
  const idleFBX = useFBX('/animations/Breathing Idle.fbx')

  // Clone animation clips and set their names for reactivity/type safety
  const walkingClip = walkingFBX.animations?.[0]?.clone()
  if (walkingClip) { walkingClip.name = 'Walking' }
  const idleClip = idleFBX.animations?.[0]?.clone()
  if (idleClip) { idleClip.name = 'Idle' }
  // Only pass defined clips
  const animationClips = [walkingClip, idleClip].filter(Boolean) as THREE.AnimationClip[]

  // Pass the clips to useAnimations, then manage which one to play by name
  const { actions } = useAnimations(animationClips, group)

  const currentAnimation = useRef<'Walking' | 'Idle'>('Idle')
  const setAnimation = useCallback((next: 'Walking' | 'Idle') => {
    if (currentAnimation.current === next) return
    const prevAction = actions[currentAnimation.current]
    const nextAction = actions[next]
    prevAction?.fadeOut(0.25)
    nextAction?.reset().fadeIn(0.25).play()
    currentAnimation.current = next
  }, [actions])

  useEffect(() => {
    actions.Idle?.reset().fadeIn(0.25).play()
    return () => {
      actions.Idle?.fadeOut(0.2)
      actions.Walking?.fadeOut(0.2)
    }
  }, [actions])
  
  const lastScrollY = useRef(window.scrollY)
  const scrollDelta = useRef(0)
  
  useEffect(() => {
    const handleScroll = () => {
      scrollDelta.current = window.scrollY - lastScrollY.current
      lastScrollY.current = window.scrollY
    }
    window.addEventListener('scroll', handleScroll, { passive: true })
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])
  
  const smoothDelta = useRef(0)
  

  useFrame(() => {
    if (group.current) {
      smoothDelta.current = lerp(smoothDelta.current, scrollDelta.current, 0.5)
      scrollDelta.current = 0

      const delta = smoothDelta.current
      let rotation = delta > 0 ? Math.PI / 2 : 0
  
      if (Math.abs(delta) > 1) { // pixels instead of normalized 0–1 offset
        setAnimation('Walking')
        rotation = delta > 0 ? Math.PI / 2: -Math.PI / 2
      } else {
        setAnimation('Idle')
      }
  
      group.current.rotation.y = lerp(group.current.rotation.y, rotation, 0.1)
      scrollDelta.current = 0 // reset each frame
    }
  })


  return (
    <group ref={setGroupRef} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Streamoji_Avatar"
            geometry={nodes.Streamoji_Avatar.geometry}
            material={materials.Streamoji_Avatar}
            skeleton={nodes.Streamoji_Avatar.skeleton}
            castShadow
          />
        </group>
        <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Streamoji_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          castShadow
        />
        <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Streamoji_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          castShadow
        />
        <skinnedMesh
          name="Streamoji_Head"
          geometry={nodes.Streamoji_Head.geometry}
          material={materials.Streamoji_Skin}
          skeleton={nodes.Streamoji_Head.skeleton}
          morphTargetDictionary={nodes.Streamoji_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Streamoji_Head.morphTargetInfluences}
          castShadow
        />
        <skinnedMesh
          name="Streamoji_Teeth"
          geometry={nodes.Streamoji_Teeth.geometry}
          material={materials.Streamoji_Teeth}
          skeleton={nodes.Streamoji_Teeth.skeleton}
          morphTargetDictionary={nodes.Streamoji_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Streamoji_Teeth.morphTargetInfluences}
          castShadow
        />
      </group>
    </group>
  )
})

useGLTF.preload('models/Avatar.glb')