/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dudzy (https://sketchfab.com/Dudzy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bilboard-0592500b0a104965b85e66c5ddf29dfe
Title: Bilboard
*/

import * as THREE from "three";
import React, { useState } from "react";
import { useCursor, useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    direk1_direk_0: THREE.Mesh;
    boru_boru1_0: THREE.Mesh;
    ["ba��lant��1_baglanti_0"]: THREE.Mesh;
    ekran_ekran1_0: THREE.Mesh;
    kasa_kasa1_0: THREE.Mesh;
    ["ba��lant��2_baglanti_0"]: THREE.Mesh;
    direk2_direk_0: THREE.Mesh;
  };
  materials: {
    direk: THREE.MeshStandardMaterial;
    boru1: THREE.MeshStandardMaterial;
    baglanti: THREE.MeshStandardMaterial;
    ekran1: THREE.MeshStandardMaterial;
    kasa1: THREE.MeshStandardMaterial;
  };
};

export function BillBoard({
  texture,
  ...props
}: React.ComponentProps<"group"> & { texture?: THREE.Texture; link?: string }) {
  const { nodes, materials } = useGLTF(
    "/models/Bilboard (1).glb",
  ) as unknown as GLTFResult;

  const [hovered, setHovered] = useState(false);

  useCursor(hovered);

  const handleClick = React.useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      if (props.link) {
        window.open(props.link, "_blank", "noopener,noreferrer");
      }
    },
    [props.link]
  );

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.direk1_direk_0.geometry}
          material={materials.direk}
          position={[-4.219, 0, 0.184]}
          scale={0.296}
          castShadow receiveShadow
        />
        <mesh
          geometry={nodes.boru_boru1_0.geometry}
          material={materials.boru1}
          position={[0, 2.673, 0.64]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.151}
          castShadow receiveShadow
        />
        <mesh
          geometry={nodes["ba��lant��1_baglanti_0"].geometry}
          material={materials.baglanti}
          position={[0, 2.673, 0.64]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.151}
          castShadow receiveShadow
        />
        <mesh
          geometry={nodes.ekran_ekran1_0.geometry}
          material={materials.ekran1}
          position={[0, 0, 0.052]}
          castShadow receiveShadow
        />
        <mesh
          geometry={nodes.kasa_kasa1_0.geometry}
          material={materials.kasa1}
          position={[0, 0, 0.052]}
          castShadow receiveShadow
        />
        <mesh
          geometry={nodes["ba��lant��2_baglanti_0"].geometry}
          material={materials.baglanti}
          position={[7.208, 2.673, 0.64]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.151}
          castShadow receiveShadow
        />
        <mesh
          geometry={nodes.direk2_direk_0.geometry}
          material={materials.direk}
          position={[4.208, 0, 0.184]}
          scale={0.296}
          castShadow receiveShadow
        />
        <mesh
          onPointerEnter={() => setHovered(true)}
          onPointerLeave={() => setHovered(false)}
          onClick={handleClick}
          position={[0, 0, 0.5]}
          castShadow receiveShadow
        >
          <planeGeometry args={[8, 4.35]} />
          <meshStandardMaterial map={texture} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Bilboard (1).glb");
