/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jvin (https://sketchfab.com/jvin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arobase-at-logo-b06b27926ab04f989cb1d808bda03c27
Title: Arobase (at) logo
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF} from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_9: THREE.Mesh
    Object_12: THREE.Mesh
    Object_15: THREE.Mesh
    Object_18: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    Material__0: THREE.MeshStandardMaterial
    Material__1: THREE.MeshStandardMaterial
    Material__2: THREE.MeshStandardMaterial
    Material__3: THREE.MeshStandardMaterial
  }
}

// type ActionName = 'GltfAnimation 0'
// type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Email(props: React.ComponentProps<'group'>) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/models/Arobase Logo.glb') as unknown as GLTFResult
//   const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="BluffTitler_Camera_Layer_0_0" />
              <group name="BluffTitler_Text_Layer_3_1">
                <group name="Letter_X_2" position={[2, -0.47, -362]} rotation-z={Math.PI/2} rotation-x={Math.PI}  scale={[0.828, 0.828, 1.221]}>
                  <mesh
                    name="Object_6"
                  
                    geometry={nodes.Object_6.geometry}
                    material={materials.Material}
                  />
                </group>
              </group>
              <group name="BluffTitler_Text_Layer_4_3">
                <group name="Letter_X_4" position={[2, -0.47, -362]} scale={[0.828, 0.828, 1.221]}>
                  <mesh
                    name="Object_9"
                  
                    geometry={nodes.Object_9.geometry}
                    material={materials.Material__0}
                  />
                </group>
              </group>
              <group name="BluffTitler_Sketch_Layer_5_5" position={[0, 0.01, -350.8]} scale={0.5}>
                <group name="Sketch_6">
                  <mesh
                    name="Object_12"
                  
                    geometry={nodes.Object_12.geometry}
                    material={materials.Material__1}
                  />
                </group>
              </group>
              <group
                name="BluffTitler_Sketch_Layer_6_7"
                position={[1.84, -0.39, -362.4]}
                scale={0.838}>
                <group name="Sketch_8">
                  <mesh
                    name="Object_15"
                  
                    geometry={nodes.Object_15.geometry}
                    material={materials.Material__2}
                  />
                </group>
              </group>
              <group name="BluffTitler_Sketch_Layer_7_9" position={[0, 0.01, -351.6]} scale={0.5}>
                <group name="Sketch_10">
                  <mesh
                    name="Object_18"
                  
                    geometry={nodes.Object_18.geometry}
                    material={materials.Material__3}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Arobase Logo.glb')