/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul.Davidson (https://sketchfab.com/Paul.Davidson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fountain-5e236afbc2d04f2499b38108def849fe
Title: Fountain
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Model_material0_0: THREE.Mesh
    Model_material0_0_1: THREE.Mesh
    Model_material0_0_2: THREE.Mesh
    Model_material0_0_3: THREE.Mesh
    Model_material0_0_4: THREE.Mesh
    Model_material0_0_5: THREE.Mesh
    Model_material0_0_6: THREE.Mesh
  }
  materials: {
    material0: THREE.MeshBasicMaterial
  }
}

export function Fountain(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/Fountain (1).glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.007, -0.064, -0.047]} rotation={[0.089, 0.477, 0.029]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Model_material0_0.geometry}
            material={materials.material0}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Model_material0_0_1.geometry}
            material={materials.material0}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Model_material0_0_2.geometry}
            material={materials.material0}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Model_material0_0_3.geometry}
            material={materials.material0}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Model_material0_0_4.geometry}
            material={materials.material0}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Model_material0_0_5.geometry}
            material={materials.material0}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Model_material0_0_6.geometry}
            material={materials.material0}
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Fountain (1).glb')
