/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-github-logo-441d03d1076b44f483df551e02d970fe
Title: 3D Github Logo
*/

import * as THREE from 'three'
import React, { useState } from 'react'
import { useCursor, useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    glossy_putih: THREE.MeshStandardMaterial
    github: THREE.MeshStandardMaterial
  }
}

export function GitHub(props: React.ComponentProps<'group'>) {

    const [hovered, setHovered] = useState(false)

    useCursor(hovered)

    const handleClick = React.useCallback((e: React.MouseEvent) => {
        e.stopPropagation();
        window.open("https://khansameer.vercel.app/", "_blank", "noopener,noreferrer");
      }, []);
  const { nodes, materials } = useGLTF('/models/3D GitHub Logo.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} onPointerEnter={() => setHovered(true)}
    onPointerLeave={() => setHovered(false)} onClick={handleClick}>
      <group position={[-0.055, 2.945, 6.336]} rotation={[Math.PI, 0, 0]} rotation-z={Math.PI/2} rotation-x={Math.PI}  scale={28.364}>
        <mesh
        castShadow receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.glossy_putih}
        />
        <mesh
        castShadow receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.github}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/3D GitHub Logo.glb')
