/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: checomx (https://sketchfab.com/checomx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/billboard-nasa-kennedy-space-center-9843ffa8db9942e5bf673bca8720c55d
Title: Billboard Nasa Kennedy Space Center
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function InfoBoard(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/NASA Kennedy Space Center.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.012, 0, 0.012]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials['Material.001']}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            castShadow receiveShadow
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/NASA Kennedy Space Center.glb')
