/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-logo-3d-model-792093fab435419ab70dae39d2891cb3
Title: JavaScript Logo – 3D Model
*/

import * as THREE from 'three'
import React  from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    yellow: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
  }
}

export function JS(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/JavaScript Logo 3D Model.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.yellow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.black}
      />
    </group>
  )
}

useGLTF.preload('/models/JavaScript Logo 3D Model.glb')
