/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-linkedin-logo-e8786a94c6a942c594696d58d8c59a50
Title: 3D Linkedin Logo
*/

import * as THREE from 'three'
import React, { useState } from 'react'
import { useCursor, useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    glossy_linkedin: THREE.MeshStandardMaterial
    glossy_putih: THREE.MeshStandardMaterial
  }
}

export function Linkedin(props: React.ComponentProps<'group'>) {

    const [hovered, setHovered] = useState(false)

    useCursor(hovered)

    const handleClick = React.useCallback((e: React.MouseEvent) => {
        e.stopPropagation();
        window.open("https://khansameer.vercel.app/", "_blank", "noopener,noreferrer");
      }, []);

  const { nodes, materials } = useGLTF('/models/LinkedIn Logo 3D.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} onPointerEnter={() => setHovered(true)}
    onPointerLeave={() => setHovered(false)} onClick={handleClick}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 3, 6]} rotation-z={Math.PI/2} rotation-x={Math.PI} scale={0.843}>
          <mesh
          castShadow receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.glossy_linkedin}
          />
          <mesh
          castShadow receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.glossy_putih}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/LinkedIn Logo 3D.glb')
