/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/MacBook Pro.glb -o src/components/MacBookPro.jsx -r public
Laptop / MacBook Pro by Alex Safayan [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/27hcX_w47Jb)
*/

import { useGLTF, useTexture } from "@react-three/drei";
import {  type ThreeElements } from "@react-three/fiber";
import type { JSX } from "react";
import { Mesh, BufferGeometry, Material } from "three";

// Define the expected types of the nodes and materials loaded from the GLTF file
type MacBookProGLTFResult = {
  nodes: {
    mesh485226736: Mesh & { geometry: BufferGeometry };
    mesh485226736_1: Mesh & { geometry: BufferGeometry };
    mesh485226736_2: Mesh & { geometry: BufferGeometry };
    mesh485226736_3: Mesh & { geometry: BufferGeometry };
    mesh256948792: Mesh & { geometry: BufferGeometry };
    mesh256948792_1: Mesh & { geometry: BufferGeometry };
    mesh256948792_2: Mesh & { geometry: BufferGeometry };
    mesh256948792_3: Mesh & { geometry: BufferGeometry };
  };
  materials: {
    mat16: Material;
    mat23: Material;
    mat17: Material;
    mat15: Material;
    mat25: Material;
  };
};

export function MacBookPro(props: ThreeElements["group"]): JSX.Element {
  const { nodes, materials } = useGLTF("/models/MacBook Pro.glb") as unknown as MacBookProGLTFResult;
  const screenTexture = useTexture("textures/screen.jpg");
  return (
    <group {...props} dispose={null}>
      <mesh position={[0.02, 0.85, -0.66]}>
        <planeGeometry args={[2.55, 1.55]} />
        <meshStandardMaterial map={screenTexture} />
      </mesh>
      <mesh
        geometry={nodes.mesh485226736.geometry}
        material={materials.mat16}
        castShadow receiveShadow
      />
      <mesh
        geometry={nodes.mesh485226736_1.geometry}
        material={materials.mat23}
        castShadow receiveShadow
      />
      <mesh
        geometry={nodes.mesh485226736_2.geometry}
        material={materials.mat17}
        castShadow receiveShadow
      />
      <mesh
        geometry={nodes.mesh485226736_3.geometry}
        material={materials.mat15}
        castShadow receiveShadow
      />
      <mesh
        geometry={nodes.mesh256948792.geometry}
        material={materials.mat16}
        castShadow receiveShadow
      />
      <mesh
        geometry={nodes.mesh256948792_1.geometry}
        material={materials.mat23}
        castShadow receiveShadow
      />
      <mesh
        geometry={nodes.mesh256948792_2.geometry}
        material={materials.mat17}
        castShadow receiveShadow
      />
      <mesh
        geometry={nodes.mesh256948792_3.geometry}
        material={materials.mat25}
        castShadow receiveShadow
      />
    </group>
  );
}
useGLTF.preload("/models/MacBook Pro.glb");
useTexture.preload("textures/screen.jpg");
