/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Mailbox v2.glb -o src/components/Mailbox.jsx -r public
Mailbox v2 by sirkitree [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/6Y4sEKDNxcP)
*/

import { useCursor, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useState, type JSX } from "react";
import * as THREE from "three";
import { config } from "../../../constants";

import type { ThreeElements } from "@react-three/fiber"; // For group props

// --- Define proper types for nodes and materials ---
// These names group### are directly from glTF conversion, you can refine them.

type MailboxNodes = Record<string, THREE.Mesh>;
type MailboxMaterials = Record<string, THREE.MeshStandardMaterial>;

interface GLTFResult {
  nodes: MailboxNodes;
  materials: MailboxMaterials;
  [key: string]: any;
}

export function Mailbox(props: ThreeElements["group"]): JSX.Element {
  // Force type safety, through 'unknown' cast
  const { nodes, materials } = useGLTF("/models/Mailbox v2.glb") as unknown as GLTFResult;
  const [mailboxHovered, setMailboxHovered] = useState(false);
  useCursor(mailboxHovered);

  useEffect(() => {
    const emissiveColor = new THREE.Color("#ffc527");
    Object.values(materials).forEach((material) => {
      // Defensive check: only if it's a MeshStandardMaterial
      if ((material as THREE.MeshStandardMaterial).isMeshStandardMaterial) {
        (material as THREE.MeshStandardMaterial).emissive = emissiveColor;
      }
    });
  }, [materials]);

  useFrame(() => {
    Object.values(materials).forEach((material) => {
      if ((material as THREE.MeshStandardMaterial).isMeshStandardMaterial) {
        const mat = material as THREE.MeshStandardMaterial;
        mat.emissiveIntensity = THREE.MathUtils.lerp(
          mat.emissiveIntensity,
          mailboxHovered ? 0.32 : 0,
          0.1
        );
      }
    });
  });

  return (
    <group
      {...props}
      dispose={null}
      onPointerEnter={() => setMailboxHovered(true)}
      onPointerLeave={() => setMailboxHovered(false)}
      onClick={() => window.open(`mailto:${config.contact.mail}`)}
    >
      <mesh castShadow receiveShadow geometry={nodes.group2028911354.geometry} material={materials.mat17} />
      <mesh castShadow receiveShadow geometry={nodes.group513383197.geometry} material={materials.mat17} />
      <mesh castShadow receiveShadow geometry={nodes.group1044609393.geometry} material={materials.mat17} />
      <mesh castShadow receiveShadow geometry={nodes.group62313567.geometry} material={materials.mat8} />
      <mesh castShadow receiveShadow geometry={nodes.group1018199070.geometry} material={materials.mat20} />
      <mesh castShadow receiveShadow geometry={nodes.group1855928084.geometry} material={materials.mat16} />
      <mesh castShadow receiveShadow geometry={nodes.group2114715230.geometry} material={materials.mat16} />
      <mesh castShadow receiveShadow geometry={nodes.group961800690.geometry} material={materials.mat16} />
      <mesh castShadow receiveShadow geometry={nodes.group2098010904.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1048902298.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group698486446.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group513376890.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group2003878409.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1278976230.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group823787471.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1640785644.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group774986514.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group163990428.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group502275761.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1083102086.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1169220911.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group819034674.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group2122795285.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1086767079.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1548836198.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1787203505.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group781068275.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1179346883.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group731433140.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1547746947.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1121282222.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group480589545.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group796041224.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1339086745.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group195866.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1743123278.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group1580040935.geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes.group804677075.geometry} material={materials.mat20} />
    </group>
  );
}

useGLTF.preload("/models/Mailbox v2.glb");
