/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jagobo (https://sketchfab.com/Jagobo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cherry-blossom-trees-f69be55d2e4f4f73b568ebb185bd8496
Title: Cherry Blossom Trees
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

// Fixes type error: Cannot find name 'GLTF'
type GLTF = {
  nodes: { [key: string]: THREE.Mesh }
  materials: { [key: string]: THREE.Material }
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
  }
  materials: {
    bark: THREE.MeshPhysicalMaterial
    foliage: THREE.MeshPhysicalMaterial
  }
}

// Fixes type error: Cannot find namespace 'JSX'
export function SakuraTree(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/Cherry Blossom Trees.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[88.121, 0, 0]} rotation={[Math.PI / 2, 0, -1.2598]}>
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.foliage}
          castShadow
           receiveShadow
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.foliage}
          castShadow
           receiveShadow
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.bark}
        position={[-0.0661, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow
         receiveShadow
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.foliage}
        position={[-0.0661, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow
         receiveShadow
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.bark}
        position={[88.121, 0, 0]}
        rotation={[Math.PI / 2, 0, -1.2598]}
        castShadow
         receiveShadow
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.bark}
        position={[-72.2038, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow
         receiveShadow
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.foliage}
        position={[-72.2038, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow
         receiveShadow
      />
    </group>
  )
}

useGLTF.preload('/models/Cherry Blossom Trees.glb')