/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tailwind-css-logo-3d-model-f99f9434bd35448287cdb8d5512a1edc
Title: Tailwind CSS Logo – 3D Model
*/

import * as THREE from 'three'
import React  from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    blue: THREE.MeshStandardMaterial
  }
}

export function Tailwind(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/Tailwind CSS 3D Model.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.blue}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/Tailwind CSS 3D Model.glb')