/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fyrestar (https://sketchfab.com/mevedia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/threejs-60320862bf904b7ab0e032c27daf7c7c
Title: Three.js
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
}

export function THREEJS(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/three.js model.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.material_0}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/three.js model.glb')
