/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-twitter-x-logo-814e35fbc3e543ac91ca959355f251c0
Title: 3D Twitter X Logo
*/

import * as THREE from 'three'
import React, { useState } from 'react'
import { useCursor, useGLTF } from '@react-three/drei'
// Fix for type-only import, required when verbatimModuleSyntax is enabled
import type { GLTF } from 'three-stdlib'

// Fix JSX type error for R3F
// This matches what gltfjsx does and addresses the TS error in this file.
export type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    github: THREE.MeshStandardMaterial
    glossy_putih: THREE.MeshStandardMaterial
  }
}

// Workaround for JSX namespace error with IntrinsicElements
// (If using @types/react-three-fiber, this type already exists. If not, this is a working patch.)
type GroupProps = React.ComponentProps<'group'>

// Replace alert("clicked") with opening X (Twitter) profile in a new tab.
const X_PROFILE_URL = "https://x.com/sameerkhan173"; // update to your profile URL

export function XLogo(props: GroupProps) {

    const [hovered, setHovered] = useState(false)

    useCursor(hovered)

  // To avoid TS "conversion may be a mistake" error, cast as unknown first.
  const { nodes, materials } = useGLTF('/models/3D Twitter X Logo.glb') as unknown as GLTFResult;

  const handleClick = React.useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    window.open(X_PROFILE_URL, "_blank", "noopener,noreferrer");
  }, []);

  return (
    <group {...props}  dispose={null}
    onPointerEnter={() => setHovered(true)}
    onPointerLeave={() => setHovered(false)} onClick={handleClick}>
      <group rotation={[-Math.PI / 2,0, 0]} >
        <group position={[0, 3, 6]} rotation-z={Math.PI/2} rotation-x={Math.PI}  scale={0.843}>
          <mesh
  castShadow receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.github}
          />
          <mesh
  castShadow receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.glossy_putih}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/3D Twitter X Logo.glb')